#+YOUTUBE: bwnpiqN-B4w

* ESCAPE

Puedes observar la simulación completa del caso Square [[https://youtu.be/0RpVIt6iqHw][aquí]].


* Installation

** Linux

You can install Escape with the following command in the terminal:

#+BEGIN_SRC bash
  git clone https://github.com/LuisMoyaHuallpa/Programa-ESCAPE.git
  cd Programa-ESCAPE
  make
  source bashrc
#+END_SRC

#+BEGIN_HTML
<video src="https://github.com/user-attachments/assets/f538fc55-15ec-41d0-955f-261b3de92488"></video>
#+END_HTML

Link del video completo [[https://youtu.be/bwnpiqN-B4w][aquí]].

** Mac

You can install Escape with the following command in the terminal:

#+BEGIN_SRC bash
  git clone https://github.com/LuisMoyaHuallpa/Programa-ESCAPE.git
  cd Programa-ESCAPE
  make
  source bashrc
#+END_SRC

** Windows

- Open the Microsoft Store.
- Search for Ubuntu 22.04.5 LTS.
- Click the Get (or Install) button.
- Launch the Ubuntu app—this will open a terminal window.
- When prompted, choose a username and set a password. 

To install the required dependencies on Ubuntu, run:

#+BEGIN_SRC bash
  sudo apt-get update
  sudo apt install make
  sudo apt install g++
#+END_SRC


You can install Escape with the following command in the terminal:

#+BEGIN_SRC bash
  git clone https://github.com/LuisMoyaHuallpa/Programa-ESCAPE.git
  cd Programa-ESCAPE
  make
  source bashrc
#+END_SRC


** Google Colab

To install the required dependencies on Google Colab, run:

#+BEGIN_SRC bash
  !apt-get update -qq
  !apt-get install -y nano
  !apt-get install -y xdg-utils
  !apt-get install -y gnuplot
  !pip install colab-xterm
  %load_ext colabxterm
  %xterm
#+END_SRC

This will open a new terminal window where Escape installation will begin with the following command in the terminal:
#+BEGIN_SRC bash
  git clone https://github.com/LuisMoyaHuallpa/Programa-ESCAPE.git
  cd Programa-ESCAPE
  make
  source bashrc
#+END_SRC

* Requisitos

- Lenguaje: C++ (se requiere soporte para C++17)
- Compilador: GCC 9.4 o superior / Clang 10.0 o superior
- Herramientas de Construcción: 
  - GNU Make 4.2.1 (Makefile)
  - Sistema operativo:
    - Ubuntu 20.04.6 LTS
    - Ubuntu 22.04.5 LTS

* Licencia

Este proyecto se distribuye bajo los términos de la licencia MIT. Consulta el archivo [[LICENCIA][LICENSE.txt]] para más detalles.

* Documentación Adicional

Si necesitas más información sobre cómo configurar o utilizar el proyecto, revisa los siguientes recursos:
- [[/documentation/escape.pdf][Guia de usuario]]

* Historial de Cambios

A continuación se muestra el historial de cambios:

| Versión  | Fecha       | Descripción                                   |
|----------+-------------+-----------------------------------------------|
| 1.0.0    | 2025-04-07  | Versión inicial, lanzamiento del proyecto.    |



* Artículo
Los conceptos fundamentales aplicados al programa ESCAPE se publicaron en la revista [[https://www.sciencedirect.com/science/article/pii/S2212420924007854][International Journal of Disaster Risk Reduction]] y puede citarse como:

Mas, E., Moya, L., Gonzales, E., & Koshimura, S. (2024). Reinforcement learning-based tsunami evacuation guidance system. International Journal of Disaster Risk Reduction, 115, 105023.

* Financiamiento
El programa ESCAPE se desarrolló bajo el financiamiento del Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica (CONCYTEC) de Perú (Contrato No. PE501078853-2022) 






