#+YOUTUBE: bwnpiqN-B4w

* ESCAPE

Puedes observar la simulación completa del caso Square [[https://youtu.be/0RpVIt6iqHw][aquí]].
#+BEGIN_HTML
<video 
  width="640" height="360" controls 
  src="images/instalacion-linux.mp4" 
  type="video/mp4">
  Tu navegador no soporta <code>video</code>.
</video>
#+END_HTML

#+BEGIN_HTML
  <video width="640" height="360" controls>
    <source src="images/instalacion-linux.mp4" type="video/mp4">
    Tu navegador no soporta el elemento <code>video</code>.
  </video>
#+END_HTML

#+BEGIN_HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/bwnpiqN-B4w?si=FsjEjDghIxN6NDRJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
#+END_HTML

#+BEGIN_HTML
<video src="https://user-images.githubusercontent.com/760789/149676639-ffa1de49-473d-408c-96bf-0a61f83f00e1.mov"></video>
#+END_HTML


* Installation

** Linux

You can install Escape with the following command in the terminal:

#+BEGIN_SRC bash
  git clone https://github.com/LuisMoyaHuallpa/Programa-ESCAPE.git
  cd Programa-ESCAPE
  make
  source bashrc
#+END_SRC

** Mac

You can install Escape with the following command in the terminal:

#+BEGIN_SRC bash
  git clone https://github.com/LuisMoyaHuallpa/Programa-ESCAPE.git
  cd Programa-ESCAPE
  make
  source bashrc
#+END_SRC

* Requisitos

- Lenguaje: C++ (se requiere soporte para C++17)
- Compilador: GCC 9.4 o superior / Clang 10.0 o superior
- Herramientas de Construcción: 
  - GNU Make 4.2.1 (Makefile)
  - Sistema operativo:
    - Ubuntu 20.04.6 LTS
    - Ubuntu 22.04.5 LTS

* Licencia

Este proyecto se distribuye bajo los términos de la licencia MIT. Consulta el archivo [[LICENCIA][LICENSE.txt]] para más detalles.

* Documentación Adicional

Si necesitas más información sobre cómo configurar o utilizar el proyecto, revisa los siguientes recursos:
- [[/documentation/escape.pdf][Guia de usuario]]

* Historial de Cambios

A continuación se muestra el historial de cambios:

| Versión  | Fecha       | Descripción                                   |
|----------+-------------+-----------------------------------------------|
| 1.0.0    | 2025-04-07  | Versión inicial, lanzamiento del proyecto.    |



* Artículo
Los conceptos fundamentales aplicados al programa ESCAPE se publicaron en la revista [[https://www.sciencedirect.com/science/article/pii/S2212420924007854][International Journal of Disaster Risk Reduction]] y puede citarse como:

Mas, E., Moya, L., Gonzales, E., & Koshimura, S. (2024). Reinforcement learning-based tsunami evacuation guidance system. International Journal of Disaster Risk Reduction, 115, 105023.

* Financiamiento
El programa ESCAPE se desarrolló bajo el financiamiento del Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica (CONCYTEC) de Perú (Contrato No. PE501078853-2022) 






